### ISSUE TITLE
skipped services (no extractors) for apigee

### ISSUE THREAD

**Issue by badrov** [dynatrace-oss/dynatrace-gcp-monitor#374]
Hello,
can you please explain to me the concept of extractor services? because in the logs of my cluster under GCP, I encounter the following logs:

**- skipped services (no extractors): [apigee_googleapis_com_Environment, apigee_googleapis_com_ProxyV2, apigee_googleapis_com_Proxy]**

I would like to be able to activate these metrics

best regards,
Badr

**Comment by dtwwolinski** [comment]
@mmajcher

**Comment by mmajcher** [comment]
I improved the logs, this should be merged soon and released.
The improved log msg should be more clear for you :) 
https://github.com/dynatrace-oss/dynatrace-gcp-monitor/pull/378
