### ISSUE TITLE
Two risks found with aqua scanner scanning

### ISSUE THREAD

**Issue by peijunzh** [dynatrace-oss/dynatrace-gcp-monitor#393]
With aqua/scanner:2022.4.217 to scan image dynatrace/dynatrace-gcp-monitor:release-1.1.1, there are two risks with actions needed.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/104785307/226957136-f6368361-5cb6-43e9-9707-47ad24d72968.png">

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/104785307/226957248-457f9b74-df95-4519-a555-6992e53949df.png">

Could you please take a look to see if can fix them in next release?

Appreciate!

**Comment by joaquinfilipic-dynatrace** [comment]
Hello,
I'd just mark them as ack. The sensitive data file is an example from the python lib. Regarding the usage of super user, we do have some lines in our scripts to move files only (I don't know what that scanner detected). 
If you need to dig deeper, please create a ticket and add more details about those scanned risks.
