### ISSUE TITLE
Instrument dynatrace-gcp-monitor with opentelemetry

### ISSUE THREAD

**Issue by fhjfong** [dynatrace-oss/dynatrace-gcp-monitor#394]
We would like to monitor dynatrace-gcp-monitor performance with OneAgent.  Could we instrument dynatrace-gcp-monitor with opentelemetry?

**Comment by joaquinfilipic-dynatrace** [comment]
That would have to be asked (or create an RFE) in the DT community page: https://community.dynatrace.com/t5/Dynatrace-product-ideas/idb-p/DynatraceProductIdeas
