### ISSUE TITLE
How to view custom metrics in GCP after selfMonitoringEnabled is set to true?

### ISSUE THREAD

**Issue by fhjfong** [dynatrace-oss/dynatrace-gcp-monitor#395]
https://github.com/dynatrace-oss/dynatrace-gcp-monitor/blob/master/k8s/helm-chart/dynatrace-gcp-monitor/values.yaml

# Send custom metrics to GCP to diagnose quickly if your dynatrace-gcp-monitor processes and sends metrics/logs to Dynatrace properly.
# Allowed values: "true"/"yes", "false"/"no"
selfMonitoringEnabled: "false"

How do we view custom metrics in GCP after we set selfMonitoringEnabled to true?

**Comment by NematulloKozimov** [comment]
You should find what you are looking for here: 
Project in which dynatrace-gcp-monitor is running -> Metrics explorer -> Select A Metric -> Generic Task -> Custom
