### ISSUE TITLE
Add ability to deploy dynatrace-gcp-monitor Helm chart using automation tool like Terraform 

### ISSUE THREAD

**Issue by SehiiRohoza** [dynatrace-oss/dynatrace-gcp-monitor#526]
**Is your feature request related to a problem? Please describe.**
I need to automate deployment of the `dynatrace-gcp-monitor` Helm chart using Terraform. 

**Describe the solution you'd like**
The only missing information is the link to the chart repository with `index.yaml`, all the rest steps from the `deploy-helm.sh` could be easily translated into Terraform code.

**Describe alternatives you've considered**
Manual installation even using script could cause issues in case of frequent redeployment of the infrastructure.

**Additional context**
N/A

**Comment by joaquinfilipic-dynatrace** [comment]
Hey, thanks for reaching out. This is something we are thinking about, but currently there is no room for it due to priorities. We will have a ticket in our backlog, for sure, but no ETA.
