### ISSUE TITLE
can we send custom metrics into dynatrace

### ISSUE THREAD

**Issue by avinashpodisetti** [dynatrace-oss/dynatrace-gcp-monitor#529]
is there a way to send custom metrics into dynatrace using the existing  code by modifying values.yaml file or any other files ??

**Comment by joaquinfilipic-dynatrace** [comment]
Hey. When it comes to this integration, you can ingest GCP custom metrics as long as you declare them and assign it to a single GCP resource type. Then, the autodiscovery feature can be enabled (specifying that resource type in the autodiscovery-values.yaml). 
Ref: https://docs.dynatrace.com/docs/shortlink/gcp-autodiscovery#select-resources

On a general level, outside of this particular extension, any metric can be manually ingested into Dynatrace following our protocol: https://docs.dynatrace.com/docs/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol
